version: '3'

services:
  retro-game:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.properties:/retro-game/config/application.properties

  postgres:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: retro-game
    volumes:
      - postgres-data:/var/lib/postgres
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    driver: local

  redis-data:
    driver: local
